### ISSUE TITLE
[Website] Translations for the website

### ISSUE THREAD

**Issue by Baklap4** [UltraStar-Deluxe/format#11]
### Suggestion

Currently the website is available in English. What i'd like to see is that the website can be translated into multiple languages so foreign people (who do not speak English) can also understand what's going on.

How to support languages?
- [ ] Po-files (very commonly used for translations)
- [ ] Splitting docs directory up in multiple languages
- [ ] Templating the translated strings in the source to fill them in through build step

A couple of ways of how to detect the correct language:
1. Detecting the browserlanguage and fallback if not recognized
2. Change language by choosing a language like wikipedia

### Use case

English is one of the widespread languages but so are a couple of others. It'd be nice to support these languages aswell since a lot don't know English.

The languages in order:
1. Chinese simplified
2. Hindi
3. Spanish
4. French

### Extra info/examples/attachments

Let's come up with a clever way to support translations and implement it.

**Comment by rakuri255** [comment]
Maybe create a new project for continuous localization. For example, with [Weblate](https://weblate.org/)

**Comment by Baklap4** [comment]
Weblate looks very promising! Any chance you've already used this in your other projects @rakuri255 ?

**Comment by rakuri255** [comment]
@Baklap4 yes i used it. But currently only in private networks.
But hosting it online should be also easy. We need an VPS and thats it. 
Installing is very easy. You can also try it yourself with docker.

**Comment by basisbit** [comment]
Are you really sure you want to do the extra work to keep translations into x languages up to date each time there are changes and make sure those translations are all correct? I am wondering if having only English would maybe be the better version especially nowadays where every software developer knows how to use translation tools...

**Comment by marwin89** [comment]
I agree, let's keep it only in english for now and focus on the format itself.
If everything's going well and we have enough people behind this we can come up with translations anytime and re-open this @Baklap4 :)
