### ISSUE TITLE
[Website] Make use of the Project Logos

### ISSUE THREAD

**Issue by Baklap4** [UltraStar-Deluxe/format#14]
### Suggestion

Currently there are a couple of logos attached in the repository (which aren't used).
Let's contact the people of these projects and ask if they want to be on our website as a token of which projects support this idea and want to collaborate to make the best spec out there to benefit us all.

### Use case

Seeing major platforms they all tell who are using their product.. we could do the same and build a "Used by" section on the website. This will make more of an impact than written links to the respective project

### Extra info/examples/attachments

Please check a project if they gave consent.

#### Karaoke software
* [ ] [UltraStar Online](http://ultrastaronline.com/)
* [x] [UltraStar Deluxe](https://github.com/UltraStar-Deluxe/USDX)
* [x] [Performous](https://github.com/performous/performous)
* [x] [UltraStar World Party](https://github.com/ultrastares/ultrastar-worldparty)
* [x] [Vocaluxe](https://github.com/Vocaluxe/Vocaluxe)
* [ ] [MyLittleKaraoke](https://www.mylittlekaraoke.com/)
* [x] [UltraStar Play / Melody Mania](https://github.com/UltraStar-Deluxe/Play)

#### UltraStar Song Creator software
* [ ] [Yass](https://github.com/SarutaSan72/Yass)
* [x] [Yass Reloaded](https://github.com/DoubleDee73/Yass)
* [x] [Composer](https://github.com/performous/composer)
* [x] [Karedi](https://github.com/Nianna/Karedi)
* [x] [UltraStar Creator](https://github.com/UltraStar-Deluxe/UltraStar-Creator)
* [x] [UltraSinger](https://github.com/rakuri255/UltraSinger)

#### UltraStar Textfiles hosting
* [x] [USDB](https://usdb.animux.de)
* [x] [UltraStar-ES](http://ultrastar-es.org/)

#### Management Software
* [x] [USDB Syncer](https://github.com/bohning/usdb_syncer)
* [x] [UltraStar Manager](https://github.com/UltraStar-Deluxe/UltraStar-Manager)

**Comment by Baklap4** [comment]
# Issue title
Use of Logo for UltraStar Format Specification

# Issue Body
## UltraStar Format Specification
We are from the [UltraStar Format Specification project](https://github.com/UltraStar-Deluxe/format) trying to create a specification for the UltraStar text format. This specification contains a set of rules and requirements that dictate what an UltraStar textfile is and how each item should be interpreted.

### The endgoal
The endgoal for our project would be to:
* [ ] Bring the different communities on par with eachother to increase the quality of the produced textfiles
* [ ] Versionise the format so we can improve and add features to it
* [ ] Give each Tag or NoteType a definition and how it should be working

### The question
Since <this project> uses the UltraStar Format we'd like to show your logo onto our website to tell people which projects are using the Specification and which projects don't.
For any questions please reply on this issue and we'll try our best to answer the question.

# Issue Body as Markdown
<details>
<summary>Open Markdown for copy paste</summary>

```
## UltraStar Format Specification
We are from the [UltraStar Format Specification project](https://github.com/UltraStar-Deluxe/format) trying to create a specification for the UltraStar text format. This specification contains a set of rules and requirements that dictate what an UltraStar textfile is and how each item should be interpreted.

### The endgoal
The endgoal for our project would be to:
* [ ] Bring the different communities on par with eachother to increase the quality of the produced textfiles
* [ ] Versionise the format so we can improve and add features to it
* [ ] Give each Tag or NoteType a definition and how it should be working

### The question
Since <this project> uses the UltraStar Format we'd like to show your logo onto our website to tell people which projects are using the Specification and which projects don't.
For any questions please reply on this issue and we'll try our best to answer the question.
```
</details>

**Comment by marwin89** [comment]
All communities (with repositories) are contacted and have an issue about FORMAT-Project.
We have many on board, not all but many ✅ 

![ultrastar-format-spec-together](https://github.com/UltraStar-Deluxe/format/assets/63517874/2db85804-c446-490a-a52a-ffa0168d72c7)
