### ISSUE TITLE
[Spec] Add tags for online music databases

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/format#19]
### Suggestion

I suggest to add an official header field for MusicBrainz IDs (MBID).

- [musicbrainz.org](https://musicbrainz.org/) is an open music database
- the MBID could be used to identify the song, artist, and album without doubt
- the record MBID makes for a good identifier for an online score database because it uniquely identifies a song.
    - As a user, I would expect my online scores to stay the same even if I edit lyrics or make minor corrections to a song's txt file. Having an MBID could make this possible.
- the MBID could be used to grab additional information such as album art, year, genre, etc.
    - at least if not already present in the txt file
    - the [Visual Studio Code plugin](https://github.com/UltraStar-Deluxe/format/issues/18) could fetch and suggest MBIDs based on artist and title

Note that MusicBrainz is **free only for non-commercial use**.
- Commercial applications must pay a fee for their service: https://metabrainz.org/supporters/account-type

I remember that [UltraSinger](https://github.com/rakuri255/UltraSinger) is already using MusicBrainz to add information about newly created songs.

### Use case

- Fetch info about songs (e.g., year, genre)
- Uniquely identify songs (e.g. for score database)

### Examples

```
#MUSICBRAINZRECORDING:4725d53a-0771-427c-b3ad-5eb20ba62978
#MUSICBRAINZARTIST:2386cd66-e923-4e8e-bf14-2eebe2e9b973
#MUSICBRAINZRELEASE:6d24c724-9c5c-3855-9b92-bd6bfbf3ee80
```

**Comment by basisbit** [comment]
> the record MBID makes for a good identifier for an online score database because it uniquely identifies a song.

Let me quickly change the lyrics into a single note in one sentence, and suddenly I get best score on the online leaderboard.
(Not a fan of that idea, sorry)

**Comment by achimmihca** [comment]
> suddenly I get best score on the online leaderboard

This kind of cheating is probably also possible on API level.

I mean, some API needs to be exposed so users can upload their new high score. And I don't know how one should verify that the uploaded score and song id is not fake.

So, I would not try to prevent people from cheating in the first place.

**Comment by Baklap4** [comment]
Not quite sure how the Hiscores are done now, as for performous we only have a local database, not a live one. 

I think the idea is nice, but as from the format view i think it's pretty bad since we'd tie ourselves to musicbrainz id's whilst it might be possible to make it more generic?

**Comment by marwin89** [comment]
I support the idea. 👍
Is it possible to make a tag called: #MUSICDB and then put in service and [id]?
Examples:
`#MUSICDB: musicbrainz [1234567]`
`#MUSICDB: rateyourmusic [1234567]`
`#MUSICDB: vgmdb [1234567]`
In the end musicbrainz seems to be the best solution (for open source projects) these days (according to [this music database overview](https://en.wikipedia.org/wiki/List_of_online_music_databases))

**Comment by rakuri255** [comment]
I support @marwin89 idea to make it generic!

Who can say for sure that this website will life forever?
It can be shootdown in few years and then we have these deprecated IDs when it's too specific like #MUSICBRAINZID.

Do we need a list of DBs that should be supported?
Just for compatibility?

**Comment by achimmihca** [comment]
I agree, the field name should be generic.
Otherwise it may end like the MP3 tag, which is not MP3 in all cases.

For the format, I suggest to use a single header field with URL-parameter-ish syntax, i.e. `PROVIDER=ID`.

- The equals sign is easy to understand and parse (not mixed with the initial colon).
- The separator could be a comma, `&` like in URL or maybe `|`. I think `|` is easier to read.
    - escaping is an issue. When the separator is part of the id, then the value part (after the equals sign) needs to be quoted

- `#MUSICDB: musicbrainzrecord=12345|musicbrainzartist=12345|rateyourmusic="12|345"`
- `#MUSICDB: musicbrainzrecord=12345&musicbrainzartist=12345&rateyourmusic="12&345"`

> Do we need a list of DBs that should be supported

I don't think so. IMO this is an implementation detail of the player, could be a config setting, whitelist, or something else.
Thus, I argue that this should be not part of the spec (I argue the same for the #WEBSITE tag).

**Comment by marwin89** [comment]
### 2nd SUMMARY / VOTE NOW 📈 ✋ 

So here is the second summary for this issue. We are close to a final result.

Please vote for this issue till next saturday 14th oct 2023 with emoticon 🎉 / 🚀 / ❤️ .

🚀 A: #MUSICDBARTIST, #MUSICDBRECORDING, #MUSICDBRELEASE
🎉 B: #DATAARTIST, #DATARECORDING, #DATARELEASE
❤️ C: Don't introduce this feature at all

Why these tags?
- Fetch info about songs (e.g., year, genre) in editor/game/tool automatically.
- Uniquely identify songs (e.g. for online high score database) in games.

Spec doesn't define which db to use.
However we recommend Musicbrainz Database. Cause is free for open source projects. 

🚀 A
---

We add these tags to the next version v.1.1.0 / v2023

#MUSICDBARTIST:https://musicbrainz.org/artist/ffd9d946-518f-4e66-800f-994c26bf24d5
#MUSICDBRECORDING:https://musicbrainz.org/recording/04c9c416-8bb7-45ee-a040-f7295b6582a9
#MUSICDBRELEASE:https://musicbrainz.org/release/5ba06af7-e9a0-469f-8276-6d3cce43bb0e

🎉 B:
---
We add these tags to the next version v.1.1.0 / v2023

#DATAARTIST:https://musicbrainz.org/artist/ffd9d946-518f-4e66-800f-994c26bf24d5
#DATARECORDING:https://musicbrainz.org/recording/04c9c416-8bb7-45ee-a040-f7295b6582a9
#DATARELEASE:https://musicbrainz.org/release/5ba06af7-e9a0-469f-8276-6d3cce43bb0e

---

The description in the spec (website) will be something like:

> #DATAARTIST, #DATARECORDING, #DATARELEASE
> Thes tags link to online music databases. Why is that great? There are two advantages. First: By using them you enable your song editor tool or game to fetch info about songs (e.g., year, genre, cover, title, artist). Second: A game might use it to identify a song for online highscore feature.
>Use URLs from the database of your choice to identify artist, recording(=song) and release(=album that contains the song).
> We recommend musicbrainz.org for the next few years. But please check out which music databases are actually supported in your game or song editor.

**Comment by rakuri255** [comment]
I am for the tag names in `A` but not for the URL part. 
URLs will change/break over time, so they do not have a long-life time. 
What we could rather rely on are the IDs what the DB API provides us.
The IDs should normally survive such URL and API changes. 
 
Maybe use a separate tag for which Api used? So, the APP can build the URL themselves and also migrate it to a newer API version.

```
#DB:https://musicbrainz.org/ws/2/
#DBARTIST:ffd9d946-518f-4e66-800f-994c26bf24d5
#DBRECORDING:04c9c416-8bb7-45ee-a040-f7295b6582a9
#DBRELEASE:5ba06af7-e9a0-469f-8276-6d3cce43bb0e
```

For musicbrainz the Artist URL will then look like this: https://musicbrainz.org/ws/2/artist/ffd9d946-518f-4e66-800f-994c26bf24d5

**Comment by basisbit** [comment]
> This kind of cheating is probably also possible on API level.

@achimmihca Yes, it is possible on API-level, but no one has done this on API level the past couple of years, despite the communication not even having used TLS. The key part is that doing cheating on API level requires some software dev skills and a bit of time, while copy+pasting some ID in a text file can easily be done by most 10 years old kids. Thus imho this DBRELEASE is not suitable as an identifier except if your goal is to show additional information ingame for this song using (for example) musicbrainz api. For online high scores it imho is not suitable.

**Comment by rakuri255** [comment]
Let's think about that again. Do we really need the DB Link?
If you look at self-host APPs for audio like Plex, Synology Music, mstream, Jellyfin etc. [See here](https://github.com/basings/selfhosted-music-overview). They fetch the information completely on their own. And for these APPs, the artist, title, year is actually enough to determine the song exactly. Often the infos are in the ID3 tags of the mp3. Most of the time only artist and year are in the ID3 as extra info and the other fields are mostly empty. But we could provide the most important ID3 tags in the .txt as well. [See ID3 Tags](https://exiftool.org/TagNames/ID3.html)

If you are honest, a well-defined .txt that has all the info about the song is enough to find it with any API.

**Comment by achimmihca** [comment]
> If you are honest, a well-defined .txt that has all the info about the song is enough to find it with any API

True.
Guess there is no need to add it to the format.

Ok then, I am fine to close this issue as "won't implement".

---
BTW: @marwin89 thanks for your summaries, I find these pretty helpful.

**Comment by marwin89** [comment]
### SUMMARY / FINAL RESULTS 🏁 

Thanks for the discussion about MUSICDB-feature.

Here is the result:
The majority of participants already agreed not to implement this feature. Topic is closed now.

---

> BTW: @marwin89 thanks for your summaries, I find these pretty helpful.

😄 good to hear that. I'll continue this moderation.
