### ISSUE TITLE
[Spec] #AUDIO as alternative to #MP3 to specify audio file

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/format#21]
### Suggestion

Historically, the `#MP3` header field is used to specify the audio file.

However, mp3 files are not the only supported audio format.

Thus, one could argue that `#AUDIO` would be a better name for the field.

But this could only be done as an alternative to `#MP3` to not break compatibility with the thousands of existing txt files.

So there is no clear winner:
- On the one hand, #MP3 is a misleading name for the header field.
- On the other hand, two header fields with the same purpose might also be confusing.

What do you think?

### Use case

For newbies and tutorials, it might be more intuitive to use and show #AUDIO instead of #MP3.
But it is only a minor issue.

**Comment by bohning** [comment]
I would favor the support for #AUDIO (in addition to #MP3 for backwards compatibility). If USDX and others implement support, they could convert #MP3 to #AUDIO on save. The Syncer could convert it as well, but ideally usdb would support it as well so that it’s adoption spreads.

(related: why not use #VOCALS and #INSTRUMENTAL instead of the longer #VOCALAUDIO and #INSTRUMENTALAUDIO?)

**Comment by rakuri255** [comment]
#VOCALS makes no sense to me. It's just #AUDIO, #MUSIC, #AUDIOFILE.
For Karaoke #INSTRUMENTAL, #KARAOKE or #KARAOKEAUDIO would be nice

**Comment by achimmihca** [comment]
> #VOCALS makes no sense to me

This discussion has its own issue: https://github.com/UltraStar-Deluxe/format/issues/20

Please use [this issue here](https://github.com/UltraStar-Deluxe/format/issues/21) only for "#AUDIO as alternative to #MP3".

**Comment by marwin89** [comment]
Thanks for your discussion. So we have a consens here. ✅ 

I've put #AUDIO to the [Overview Version spreadsheet](https://docs.google.com/spreadsheets/d/13fj_wtRHbSjaOaS1ehmCogoeFV9MyqY1eeiqkrJfhDA/edit#gid=328136984) mentioned in #31 .

**Comment by Baklap4** [comment]
Lets write a conclusion as the completed message so it doesnt get lost in translation :)

**Comment by marwin89** [comment]
###  SUMMARY / FINAL RESULTS 🏁 
So here are the final results for this issue. 

We add this tag in version 1.1.0:
```
#AUDIO: Artist - Title of the song.mp3
``` 
We deprecate this tag in version 1.1.0:
```
#MP3: Artist - Title of the song.mp3
``` 
#MP3-Tag will be removed in version 2.0.0 (probably in 1-2 years).

The description in the spec (website) is:

> #AUDIO
> Definies the audio file that contains the whole music in one (consisting of VOCALS (the singers voice(s)) and INSTRUMENTAL(S). This is the new tag for the deprecated #MP3 tag.
