### ISSUE TITLE
[Spec] License, attribution, and source

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/format#23]
### Suggestion

Music licenses typically require attribution (notably a lot of Creative Commons licenses).

The [USDX song repository](https://github.com/UltraStar-Deluxe/songs) has a separate license.txt file to specify license details.

However, I would prefer this info in the song's txt file itself. This reduces the need for a second file.

This would also make it easer to display license and attribution to the player because it can be read like other fields from the txt file.

Note that the background image, cover image, video, and audio all may require different licenses and attribution.
Furthermore, music typically differs between lyrics, composer, artist, etc. So attribution is not trivial.

Furthermore, I think a field for the source of the audio, video, image, etc. would make sense.
This can be used to verify the named license.

For example Melody Mania uses the fields
- `...LICENSE` for the license / copyright
- `...AUTHOR` for attribution
- `...SOURCE` for link to source

```
#AUDIOLICENSE:Public Domain
#AUDIOAUTHOR:Tom Lehrer
#AUDIOSOURCE:https://tomlehrersongs.com/a-christmas-carol/
#BACKGROUNDLICENSE:Pixabay Content License
#BACKGROUNDAUTHOR:Placidplace on Pixabay
#BACKGROUNDSOURCE:https://pixabay.com/de/photos/weihnachtszeit-dekoration-7585927/
```

This should be sufficient for Creative Commons licensed stuff.
But a more thought out solution would be nice.

YouTube's license and attribution of music / video may be good for inspiration
- https://www.youtube.com/watch?v=xPU8OAjjS4k
- https://www.youtube.com/watch?v=y5x8W_zKKgk
- YouTube has at least TITLE, ARTIST, SONGWRITER, LICENSE
- YouTube also shows a short copyright and more details in the description.

Maybe there is some standard for music / video / image copyright and attribution?

**Comment by basisbit** [comment]
I am not a lawyer, but except in the case of public domain / cc-0, you usually have to distribute the full license text with it to be legally compliant. Of course if needed it should be enough to use something like `#AUDIOLICENSE:See license.txt in this here folder` when a long license text is used.

**Comment by basisbit** [comment]
Come to think of it, we could also just have the license text at the end of the file after the `E` line which marks the end of the lyrics and have `#AUDIOLICENSE:see license at the end of this here file`

**Comment by achimmihca** [comment]
> have the license text at the end of the file after the E line which marks the end of the lyrics 

That's a neat idea.

However, I would declare this as a more general comment section.
It may be used to add attribution details, but could also be used for something else. This is up to the user.
I don't think any new header field are required in this scenario.

I could live with that solution.

**Comment by achimmihca** [comment]
I just stumbled across this idea. I think it has a noble goal but it is not feasible and not needed in the context of a community grown karaoke format.

So I will close this as won't fix.
Feel free to reopen if you feel a need for this.
