### ISSUE TITLE
[Spec] Multiple entries in #GENRE / #LANGUAGE / #CREATOR

### ISSUE THREAD

**Issue by marwin89** [UltraStar-Deluxe/format#30]
### Suggestion

It would be good to have multiple entries in #GENRE, #LANGUAGE, #EDITION and #CREATOR.

Example:

`#GENRE: Rock | Grunge | Alternative`
`#LANGUAGE: English | French`
`#CREATOR: DoubleDee | Bohning | retrogirl `
`#EDITION: Eurovision | SingStar | SongChecked | Duets`

### Use case

There are a lot of songs that

1. are mixture of different genres and music styles
2. have two languages in the lyrics
3. are made, fixed or updated by more than one person
4. fit to different collections or compilations

### Extra info/examples/attachments

Which separator would be the best? 

1.  |
2.  ,
3.  /

In #19 for music database #MUSICDB we are going to have a consens to use |

**Comment by rakuri255** [comment]
I also seen `;`

**Comment by Baklap4** [comment]
How about instead of seperating on character to introduce multiple TAGS if you'd want multiple values?
```
#GENRE: Rock
#GENRE: Grune
```

this would prevent possible clashes with seperation characters vs the actual value. An issue like this was recently found by myself for usdb-syncer https://github.com/bohning/usdb_syncer/issues/169
In short: Video tag contained title which contained an `=` character which resulted in that it failed parsing

Don't get me wrong i like to have a feature where multiple values can be used for a certain tag but not sure how to make a good architecture for it

**Comment by rakuri255** [comment]
> How about instead of seperating on character to introduce multiple TAGS if you'd want multiple values? And read all lines starting with a certain tag.
> 
> ```
> #GENRE: Rock
> #GENRE: Grune
> ```
> 
> this would prevent possible clashes with seperation characters vs the actual value. An issue like this was recently found by myself for usdb-syncer [bohning/usdb_syncer#169](https://github.com/bohning/usdb_syncer/issues/169) In short: Video tag contained title which contained an `=` character which resulted in that it failed parsing
> 
> Don't get me wrong i like to have a feature where multiple values can be used for a certain tag but not sure how to make a good architecture for it

I think most other programs use a separator by default rather than using the tag multiple times. I am thinking of csv files as an example.

**Comment by rakuri255** [comment]
UltraSinger currently uses `,` and in #Comments` it uses `|` and `,` for readability when there are 2 separated things..

```
#GENRE:Metal,Rock
#COMMENT:UltraSinger [GitHub] | Score: total: 6825, notes: 6161 line: 664, golden: 0
```

**Comment by marwin89** [comment]
Which separator would you like the most? Please vote by using emoticon-reactions:
| Vote | separator | result
|--------|--------|--------|
| 😄 | = pipe |
| ❤️ | = colon |
| 🚀| = semi colon |
| 🎉 | = combination of pipe an semi colon |

**Comment by bohning** [comment]
Most natural and easy to type is a comma-separated list

**Comment by Baklap4** [comment]
To ellaborate on the `|` vote. This is barely used in any normal written stuff, whereas comma and semicolons are far more likely to be used.

If the element can only contain one word then i'd go for comma or semicolon. z
If the element can have more than one word i'd use a pipe

**Comment by marwin89** [comment]
It's just one word per entry. I'll define in summary below. Let's use comma and end this discussion here.

###  SUMMARY / FINAL RESULTS 🏁 
So here are the final results for this issue. 

We enable multiple entries in #GENRE, #LANGUAGE, #CREATOR and #EDITION in version 1.1.0 via  separator. Separator is comma ","
```
#GENRE: Indie-Rock, Grunge, Alternative
#LANGUAGE: English, French
#CREATOR: DoubleDee, Bohning, retrogirl 
#EDITION: Eurovision, Checked, Duets, Christmas, Halloween, SingStar, RockBand
``` 
The description in the spec (website) will be complemented with these infos:

> #GENRE
> ...
> This tag allows multiple entries, you separate them with comma. An entry consists of one word. Use "-" for substyles Synth-Pop, Indie-Pop etc. Right now there is a limit up to 255 Characters. So can add a lot of fitting genres.
> #LANGUAGE
> ...
> This tag allows multiple entries, you separate them with comma. An entry should consists of one word.
> #CREATOR
> ...
> This tag allows multiple entries, you separate them with comma. An entry should consists of one word.
> #EDITION
> ...
> This tag allows multiple entries, you separate them with comma. An entry of edition consists ideally of one word.

**Comment by Baklap4** [comment]
Not quite sure if all these fields are only containing one thing per instance..

GENRE => Alternative Rock, Heavy Metal, New Wave
Creator => Names can have spaces in them
EDITION => Singstar Rocks, SingStar 90"s, Disney Sing Along

Language is probably the only one with only one  word :o

**Comment by bohning** [comment]
I agree with @Baklap4, they can be multiple words, but I don’t see a problem with that, as long as there are no commas in the entries (most likely not the case for any of the three).
