### ISSUE TITLE
[Spec] Define Versions: 0.1.0 till 1.1.0

### ISSUE THREAD

**Issue by marwin89** [UltraStar-Deluxe/format#31]
### Suggestion

According to #13 strategy: 

1. We need to define a version for undefined song txt-files first. 
2. This version represents all text files that we currently host on usdb.animux (as of today 2023 Sep 26th) and other txt-file-hostings. 
3. This version defines the bare minimum that every song needs to played and hosted.
4. Do you have a draft already? Please post in this issue and lets discuss.

### Use case

Start versioning. Having a version we can build up upon and categorize txt-file entries in hostings.

### Extra info/examples/attachments

- Don't know if "v.0.1.0" is appriopiate. please discuss
- We definitely need a version tag #VERSION at the start of a txt-file mentioned in #13.

**Comment by marwin89** [comment]
To get things startet. What about this? Please add or correct 🙏 

```
#VERSION: 0.1.0
#TITLE: Title of the song
#ARTIST: Name of the Artist
#MP3: Filename auf the audio file.mp3
#COVER: Covername.jpg
#BACKGROUND: Background.jpg
#VIDEO: Video.mp4
#GAP:12.4
+Normal Notes
+Golden Notes
+Freestyle Notes
+Rap Notes
+Golden Rap Notes
E
```
Out of scope for this version: duet, medley, vocals, instrumental, etc.?

**Comment by Baklap4** [comment]
I'd define version 0.1.0, but also treat every file without a `#VERSION` tag to be 0.1.0. This should be mentioned somewhere
Maybe @bohning can include the new tag upon downloading through USDB_Syncer, maybe that AnimuxAlex can include it for every txt file on the server

As for bare minimum i'd only include the header tags:
* Artist
* Title
* MP3
* BPM

Things like covers and backgrounds are all optional

for the notetypes i'd say:
* Normal notes
* E

**Comment by marwin89** [comment]
Here is a new spreadsheet table page for us to organize the versions. edit as you like:

[Versions Overview spreadsheet](https://docs.google.com/spreadsheets/d/13fj_wtRHbSjaOaS1ehmCogoeFV9MyqY1eeiqkrJfhDA/edit#gid=328136984)

![format-versions-spreadsheet](https://github.com/UltraStar-Deluxe/format/assets/63517874/d57cc3ab-8e5c-436f-a144-72c124906245)

**Comment by marwin89** [comment]
Updated format version spreadsheet: 📝

🔗 [Versions Overview Spreadsheet](https://docs.google.com/spreadsheets/d/13fj_wtRHbSjaOaS1ehmCogoeFV9MyqY1eeiqkrJfhDA/edit#gid=328136984)

Please mind: release date of format versions and implementation date are different things. You decide when the new versions are implemented in your software

![format-versions-spreadsheet-2](https://github.com/UltraStar-Deluxe/format/assets/63517874/c640e05f-6331-4b53-81c3-f94fd03465cb)

**Comment by Nianna** [comment]
The spreadsheet is a nice idea but it would be nice if it contained all information and was a single point of truth. Now by looking just at it I feel like I'm missing half of the info that is probably spread over various issues here on github.

Could you please add info why the tags were deemed deprecated and why others were renamed?
For example I don't see why we would want to rename #MEDLEYENDBEAT to #MEDLEYEND? Is there any gain in that?

Also, what are the new tags supposed to mean? e.g. #ONLINE ?

**Comment by rakuri255** [comment]
Do we need `E` end of file? I mean it is clear to every software when end of file is. You don't need to define that extra.

**Comment by marwin89** [comment]
I've updated the spreadsheet

[Version overview spreadsheet](https://docs.google.com/spreadsheets/d/13fj_wtRHbSjaOaS1ehmCogoeFV9MyqY1eeiqkrJfhDA/edit#gid=328136984)

![format-versions-spreadsheet-3](https://github.com/UltraStar-Deluxe/format/assets/63517874/b2c221c0-99b0-4bdd-8306-cdd0172bb71a)

**Comment by Baklap4** [comment]
> Do we need `E` end of file? I mean it is clear to every software when end of file is. You don't need to define that extra.

I'm not quite sure why `E` was a thing to begin with. Maybe someone can explain how it got into place?
As @rakuri255 mentioned for developers end-of-file is easy enough to detect. Maybe a usecase for non-developers we might miss?

**Comment by Baklap4** [comment]
> I just meant to use it as a single point of truth while we work on the draft, with tags being linked to the related issues for reference. Just like @marwin89 did, thanks for that 👍

Yes very nice!

> It's just not gonna happen. Also it will not update the songs that users have locally. Without any tool that we can tell the user to use, all formats will have to be supported like forever. But I never meant it to be a part of this project, so it's unrelated to this issue.

The tool to use at least for usdb could be maybe the USDB-syncer.  There's an open issue on how to stay up to date which will need some more clarification (and thus getting users over to the latest versions).

> I still do not see the point of having v0.1.0. Same with v0.3.0 - new version just to deprecate some tags?
> Why can't we have just one version instead of these 3?

Why do we want version 0.1.0 -> Karaoke software just starting out which want to play an ultrastar song can build their software with just these tags/notes and they'll have a working karaoke. This is the mvp (minimal viable product) and is often used to get a project started.

With 0.2.0 we (format project) want to specify tags that are already out there. This is mainly for compatibility with the already existing songs out there. Some songs qualify for 0.2.0 from the start, some won't.

Version 0.3.0 is used to clear up the mess we made over the past decade. It's nice for developers to deprecate things to give them a heads up of what's going to change and maybe a why it's going to change and what to use instead.

Then from version 1.0.0 this mess is cleared up (and thus we introduce a major bump since it'll break some karaoke programs).

I think the transition from 0.1.0 to 1.0.0 can be mostly automated and thus it wouldn't be needed to support all of these versions. It's mainly a reference point to show how this project evolved what led to version 1.0.0

> As you have said yourself- all tools will have to implement all versions. Why make the life harder for everyone and define 3 versions instead of 1?

The different softwares out there can decide themselves what version they want to support. A strategy is mentioned in the sheet. With the help of #32 software can show what they support and what not.

> We could define a list of required tags, a list of optional tags + info which tags are deprecated (and what should be used instead if applicable).

The required list of tags (for atleast version 1.0.0 - and everything before that -) are all the tags listed in v0.1.0. All other tags are optional.

**Comment by marwin89** [comment]
FYI:  [OVERVIEW Spreadsheet](https://docs.google.com/spreadsheets/d/13fj_wtRHbSjaOaS1ehmCogoeFV9MyqY1eeiqkrJfhDA/edit#gid=81758435) updated (semver strategy vs anual strategy)
![format-versions-spreadsheet-4b](https://github.com/UltraStar-Deluxe/format/assets/63517874/6ea7c2bf-226f-4187-851f-efc26d961c28)

**Comment by marwin89** [comment]
Pre-Condition for this issue:
we need to agree on version strategy #13 first to continue this issue. There is a voting till 14th oct 2023.

**Comment by achimmihca** [comment]
> With 0.2.0 we (format project) want to specify tags that are already out there.

I think this is beneficial for communication with users.
You can just point them to the spec and from there they can find how the format changed and thus how to update their songs.

**Comment by marwin89** [comment]
## Summary / Final Results 🚩 

Thanks for discussing version structure. We voted for this in issue:
- #13 

Here are the final results.


### Result:

- We structure Versions starting from minimum. This ensures traceability.
- First real version is 1.0.0.
- We have a complete version table from 0.1.0 to 2.0.0 (2023-2025).
- Version table will be uploaded to usdx.eu/format website

### Version Table:

![Image](https://github.com/UltraStar-Deluxe/format/assets/63517874/e8069afc-20b8-4032-8d0a-24c0549b2ba3)

### Details:

Our versions will start with this structure
0.1.0 -> Bare Minimum, Minimum vial product (mvp)
0.2.0 -> Introduce the tags we currently have
0.3.0 -> Deprecate old # tags we don't wanna use (duplicates, technical not nessecary)
1.0.0 -> Removal of deprecated tags and final list of currently used tags (2023)
1.1.0 -> First new features we want to introduce, deprecated #mp3 and chaotic time units (2023)
~1.2.0 -> more new features (2024)
2.0.0 -> Removal of #MP3 and introduce unified time units (=doing breaking changes) (2025)
