### ISSUE TITLE
[Spec] Additional info of song and artist with #INFO

### ISSUE THREAD

**Issue by rakuri255** [UltraStar-Deluxe/format#33]
### Suggestion

How about adding more infomation about the singer / song?
Musicbrainz and Discorgs would have additional information. 
It is always interesting to know more about the history of the artist or the song itself.

For example: [Discogs: Michael Jackson](https://www.discogs.com/artist/15885-Michael-Jackson)

You could add everything here in one tag: `#Info`.

Or leave it to the game to get the additional info. But that would mean that you always need inet access.

**Comment by Baklap4** [comment]
I saw this also within aegisub karaoke land. They usually add list all the singers of the band (if there are more than one)  aside from the band name. This is a nice extra. Other info might fit in here aswell.

@rakuri255 what would the scope of `#INFO` be?

**Comment by Nianna** [comment]
This seems like some optional feature of a karaoke game. As you said, the game can just download the info from online if needed - be it info about singer, band members, background info about the song. You will have the newest reliable info instead of some random stuff that creator wrote years ago.

By adding new tag to the format we expect all apps to support it. I do not believe that this tag is worth it.

**Comment by Nianna** [comment]
Also I see that we already have #COMMENT tag in the format specification for some "additional info"

**Comment by marwin89** [comment]
@rakuri255 in #19 OnlineMusicDatabase (voting-phase) we would introduce a tag like #DATAARTIST (besides #DATARECORDING, #DATARELEASE) to get information about artist in a technical database way. Maybe this is basically the same.

```
#DATAARTIST:https://musicbrainz.org/artist/f27ec8db-af05-4f36-916e-3d57f91ecf5e
```

**Comment by rakuri255** [comment]
@marwin89 Yes, the database could contain such information, but it does not have to. The info could have been collected from several databases and then entered into the txt. My idea was actually an offline use. That you already have all the information in offline mode.  

I agree with you that the apps should get the information themselves, then they have more truth behind it.
