### ISSUE TITLE
[Spec] Case insensitive header fields

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/format#36]
### Suggestion

Why are header fields in all uppercase? Is this a convention or enforced by the format?

By defining header field names as case insensitive, one could make the format more robust and readable.

The following would then be equivalent

```
#VIDEOGAP: 1.2
```

```
#videogap: 1.2
```

```
#videoGap: 1.2
```

```
#VideoGap: 1.2
```

### Use case

Use camelCase or PascalCase for header field names, e.g., #MedleyStartBeat

**Comment by basisbit** [comment]
I'd consider the different options to all be approximately similar good for the task. Thus it might be better to just keep it the way it has been the past 15 years or so, unless I am missing an important reason.

**Comment by achimmihca** [comment]
Ok. It is surprisingly consistent at the moment and it's not causing trouble.
So I guess better not change a good running system.

So, this issue can be closed as "won't implement"
