### ISSUE TITLE
Setting up repository settings and merge rules and basic templates

### ISSUE THREAD

**Issue by Baklap4** [UltraStar-Deluxe/format#4]
Setting up a basic repository:
- [x] Repository Settings
- [x] Protected branches
- [x] Some basic templates regarding issues / prs for consistency
- [x] Contributing guide
- [x] README
    - [x] Links to the major parties involved
        - [x] USDX
        - [x] World Party
        - [x] Vocaluxe
        - [x] Performous
        - [x] MyLittleKaraoke
        - [x] USDB website
        - [x] ultrastar-es website
        - [x] Yass (reloaded?)
        - [x] composer
        - [x] Karedi
        - [x] UltraStar Creator
        - [x] UltraStar Manager
        - [x] USDB-Syncer

**Comment by bohning** [comment]
Don't forget UltraStar Creator and UltraStar Manager :⁠-⁠)

**Comment by Baklap4** [comment]
> Don't forget UltraStar Creator and UltraStar Manager :⁠-⁠)

Added them aswell as USDB-Syncer

## Changes so far
Some things for this story don't require a PR. I've posted the changes made below so it's transparent for everyone 👍 

### Repository Settings
* ✅ Disabled Wiki and Project tabs
* ✅ Linear history -> AKA rebase merge
* ✅ Auto delete head branches (when merged)

### Protected branches

* ✅Branch Name Pattern: `main`
* ✅Require pull request before merge
    * ✅Require a minimum of 1 approval
    * ✅Dismiss stale pull request approvals when new commits are pushed
* ✅Require status checks to pass (we currently don't have any)
    * ✅Require branches to be up-to-date before merge
* ✅Require conversation resolution before merging
* ✅Require linear history
* ✅Lock the main branch
* ✅Do not allow bypassing the above settings (prevents admins to push directly to main)

Continueing with templates in a bit

**Comment by Baklap4** [comment]
PR is added to do the other changes #5

**Comment by rakuri255** [comment]
Missing UltraStar Play? 
They not supporting all known tags and added 2 new tags [PreviewEnd](https://github.com/rakuri255/Ultrastar_txt_documentation#previewend) and 
[VOCALS](https://github.com/rakuri255/Ultrastar_txt_documentation#vocals)

**Comment by Baklap4** [comment]
> Missing UltraStar Play? They not supporting all known tags and added 2 new tags [PreviewEnd](https://github.com/rakuri255/Ultrastar_txt_documentation#previewend) and [VOCALS](https://github.com/rakuri255/Ultrastar_txt_documentation#vocals)

Ahh my bad i forgot that one. Adding it later tonight, thanks for the headsup
